### ISSUE TITLE
Different pin input method suggestion

### ISSUE THREAD

**Issue by nukeportugal** [jim17/memtype#12]
Instead of a base 10 pin with 4 digits where you have to press up or down to change the current digit, use a base 4 pin with 8 digits where each direction in the joystick represents a number. This would present a few advantages:
- Pin entry would always be a constant 8 steps instead of 4 to 24 steps (pin 0000 or pin 5555)
- Will result in more pin combinations (4^8 = 65536 vs 10^4 = 10000)
- Makes it easier to input the pin without looking at the screen (maybe even make it type "pass: " and fill with asterisks as you input the pin or blink a led for every digit)

What do you think?
Great project by the way.

**Comment by oyzzo** [comment]
Hi @nukeportugal!

Thanks for your comment!

We took that approax into account when designing the pin validation at the very beginning of the project, you are right in the 3 "pros" that you write in favor of using base 4 pin.

The main reason was that the human brain is way better remembering a small 4 digit decimal number than a longer series of joystick directions. You are right that we've got 10K combinations instead of 65K, but that's the same order of magnitude and doesn't make any difference in case of memory dump and brute force attack, using more digits would, but it'd imply using too long to remember PINs in any base.

One of the mains goals of the MemType device is to be easy to use, and the main security point on it is having it phisically with you, in case of loss a reasonable amount of security is needed, but keeping in mind it can not add too much difficulty of use or it'll be useless because nobody will use it.

We're currently working on a more professional focused version from scratch with a totally different core that will allow us to improve capacity, security, usability and with more features.
